W4D5/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
end

W4D5/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W4D5/app/models/band.rb
class Band < ApplicationRecord
  validates :name, :band_owner_id, presence: true

  belongs_to :owner,
    primary_key: :id, 
    foreign_key: :band_owner_id,
    class_name: :User
end

W4D5/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
require 'bcrypt'

class User < ApplicationRecord
  validates :password, length:{minimum: 6, allow_nil: true}
  validates :email, uniqueness: true, presence: true 
  validates :session_token, presence: true 
  validates :password_digest, presence: true 

  before_validation :ensure_session_token

  has_many :bands,
    primary_key: :id, 
    foreign_key: :band_owner_id,
    class_name: :Band 

  attr_reader :password 

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user 
    else  
      return nil 
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token 
  end
 
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

W4D5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :auth_token

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    session[:session_token] = nil
    if current_user
      current_user.reset_session_token!
    end 
  end

  def logged_in?
    !!current_user
  end

  def auth_token
  "<input
    type='hidden'
    name='authenticity_token'
    value='#{form_authenticity_token}'
  />".html_safe
  end

end

W4D5/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :verify_band_ownership, only: [:edit, :update, :destroy]
  before_action :verify_logged_in, only: [:new, :edit, :update, :destroy]
  before_action :set_current_band

  def set_current_band
    @current_band ||= nil 
  end

  def new
    render :new
  end

  def create
    @band = Band.new(name: params[:band][:name], band_owner_id: current_user.id) 
    if @band.save!
      redirect_to band_url(@band)
    else  
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def index
    @bands = Band.all 
    render :index 
  end

  def show
    @band = Band.find(params[:id])
    @current_band = @band.id 
    render :show 
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(name: params[:band][:name])
      redirect_to band_url(@band)
    else 
      flash[:errors] = @band.errors.full_messages
      redirect_to edit_band_url(@band)
    end
  end

  def destroy
    band = Band.find(params[:id])
    if band.delete
      redirect_to bands_url 
    else 
      flash[:errors]
      redirect_to edit_band_url(@band)
    end
  end

   def verify_band_ownership
    if !current_user.bands.include?(Band.find(params[:id]))
      flash[:errors] = 'Cannot edit a band you did not create'
      redirect_to band_url(Band.find(params[:id]))
    end 
  end

  def verify_logged_in
    if current_user.nil?
      flash[:errors] = 'Must be logged in to edit/create a band'
      redirect_to bands_url
    end
  end

end

W4D5/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new 
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user 
      login_user!(user)
      redirect_to user_url(user)
    else 
      flash.now[:errors] = 'No user found matching those credentials'
    end 
  end 

  def destroy
    logout!
    redirect_to bands_url
  end

end

W4D5/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.new(email: params[:user][:email], password: params[:user][:password])
    if user.save
      login_user!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    render :show
  end

end

W4D5/app/helpers/application_helper.rb
module ApplicationHelper
end

W4D5/app/views/bands/edit.html.erb
<h2>Edit your band</h2>

<form action="<%=band_url(@band)%>" method="post">
<input type="hidden" name="_method" value="patch">

  <%=auth_token%>
  <label for="band_name">Band Name:</label>
  <input id="band_name" type="text" name="band[name]" value="<%=@band.name%>">

  <input type="submit" value="Change Band Name">

  <br><br>
    <a href="<%=band_url(@band)%>">Discard changes</a>
  <br><br>
    <a href="<%=bands_url%>">See all bands!</a>
  <br><br>
    <form action ="<%=band_url(@band)%>" method="post">
    <input type="hidden" name="_method" value="delete">
      <%=auth_token%>
      <input type="submit" value ="Delete this band">
    </form>
    <% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>
</form>

W4D5/app/views/bands/index.html.erb
<h2>Check out all the bands!</h2>
<a href="<%=new_band_url%>">Add a band</a>

<br><br>

<div>
    <% if current_user.nil? %>
      <a href="<%= new_session_url %>">Sign in</a>
      <br><br>
      <a href="<%= new_user_url %>">Sign up</a>
    <% else %>
      <form action="<%= session_url %>" method="post">
        <%=auth_token%>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Logout">
      </form>
    <% end %>
    </div>

<section>
  <%@bands.each do |band|%>
    <h3><%=band.name%></h3>
    <a href="<%=band_url(band)%>">Visit this band's page</a>
    <br><br>
  <%end%>
</section>
 <section>
  <% if flash[:errors] %>
  <%= flash[:errors] %>
  <% end %>
  </section>

W4D5/app/views/bands/new.html.erb
<h2>Register Your Band!</h2>

<form action="<%=bands_url%>" method="post">
  <%=auth_token%>
  <label for="band_name">Band Name:</label>
  <input id="band_name" type="text" name="band[name]">

  <input type="submit" value="Add Band">

  <br><br>
  <a href="<%=bands_url%>">See all bands!</a>
  <% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>
</form>

W4D5/app/views/bands/show.html.erb
<h2><%=@band.name%></h2>

<a href="<%=edit_band_url(@band)%>">Edit band</a>
<br><br>
<a href="<%=bands_url%>">Return to all bands</a>
 <section>
  <% if flash[:errors] %>
  <%= flash[:errors] %>
  <% end %>
  </section>

W4D5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

W4D5/app/views/users/new.html.erb
<h1>Music App</h1>

<form action="<%=users_url%>" method = "post">

  <%= auth_token %>

  <label for="email">Email:</label>
  <input id="email" type="text" name="user[email]">

  <label for="password">Password:</label>
  <input id="password" type="password" name="user[password]">

  <input type="submit" value="Login">

    <br><br>
    <a href="<%=bands_url%>">See all bands!</a>
  <br><br>
  <% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>

</form>

W4D5/app/views/users/show.html.erb
<h2><%="Welcome #{current_user.email}"%></h2>
<a href="<%=bands_url%>">Check out bands</a>